---
all:
  children:
    freeipa:
      hosts:
        freeipa.local:
          ansible_host: 192.168.56.14

    keycloak:
      hosts:
        keycloak.local:
          ansible_host: 192.168.56.12

    sonarqube:
      hosts:
    sonar.local:
          ansible_host: 192.168.56.18

  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_python_interpreter: /usr/bin/python3
